
'use strict';const $=x=>document.getElementById(x),sleep=m=>new Promise(r=>setTimeout(r,m)),R=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const HEROES=[['Borik Spaccabotti','Barbaro','🧔','+1 Sbronza → +2 combattimento','#bc5938'],['Merlò il Confuso','Mago','🧙','+1 prossimo combattimento','#7558bd'],['Elira Occhio di Vino','Ranger','🧝‍♀️','Rivela una stanza','#4a9159'],['Sir Brindisi','Paladino','🛡️','Annulla una penalità','#c7a449'],['Nix Mano Lesta','Ladra','🥷','Ruba una moneta','#466e9b'],['Morgana Malto Nero','Strega','🧙‍♀️','Annulla una Maledizione','#813e7b']];
const THEMES=[['Cripta degli Sbronzi','crypt','monster'],['Cantina Proibita','cellar','curse'],['Tesoreria Reale','treasure','coin'],['Cucine Reali','kitchen','heal'],['Mercato Nero','market','loot'],['Forgia Infernale','forge','monster'],['Biblioteca Polverosa','library','mixed'],["Laboratorio dell'Alchimista",'lab','mixed'],['Corridoio delle Eco','hall','empty']];
const MON=[['Goblin Spillatore',6,1],['Scheletro Brindante',7,1],['Orco del Fusto',8,2],['Mimic Boccale',9,2],['Cavaliere Sbronzo',10,2],['Oste Non-Morto',11,3]];const BOSSES=[['Luppolax',11],['Re Malto III',12],['Demone del Boccale',14]];
let sel=-1,G=null,scene,camera,renderer,group,pawns=new Map(),monsters=new Map(),yaw=.8,dist=20,drag=false,lx=0,ly=0;const CELL=9.5;
function show(id){['home','setup','game'].forEach(x=>$(x).classList.add('hidden'));$(id).classList.remove('hidden')}function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),1600)}
function renderHeroes(){$('heroes').innerHTML=HEROES.map((h,i)=>`<div class="hero ${sel===i?'sel':''}" data-i="${i}"><div class="heroFace">${h[2]}</div><b>${h[0]}</b><small>${h[1]}<br>${h[3]}</small></div>`).join('')}
$('soloBtn').onclick=()=>{show('setup');renderHeroes()};$('rulesBtn').onclick=()=>modal('Come si gioca','Tira 1D6 per i passi. Il combattimento usa 2D6. I mostri battuti spariscono; quelli che ti battono restano. Se perdi contro un mostro torni alla Taverna ma mantieni i passi ancora disponibili. A Sbronza 10 vai KO e il turno termina. Raccogli 3 Sigilli e sconfiggi il Boss.',[['CHIUDI','ok','alt']]);$('backBtn').onclick=()=>show('home');$('heroes').onclick=e=>{let c=e.target.closest('.hero');if(c){sel=+c.dataset.i;renderHeroes()}};
function player(id,name,hi,ai){return{id,name,hi,ai,s:0,coins:2,sig:0,x:0,y:0,bonus:0,once:false,used:false,ko:false}}
function A(){return G.ps[G.turn]}function key(x,y){return x+','+y}function drunk(s){return s>=6?2:s>=3?1:0}
$('startBtn').onclick=()=>{if(sel<0)return toast('Scegli un eroe');if(!window.THREE)return alert('Il motore 3D non è disponibile. Ricarica la pagina.');let n=$('playerName').value.trim()||'Avventuriero',ai=+$('difficulty').value,rest=HEROES.map((_,i)=>i).filter(i=>i!==sel).sort(()=>Math.random()-.5),ps=[player('p',n,sel,false)];for(let i=0;i<ai;i++)ps.push(player('a'+i,['Gobbo Bot','Oste Bot','Mastro Bot'][i],rest[i],true));G={ps,turn:0,round:1,phase:'roll',moves:0,busy:false,dice:[1,1],rooms:{'0,0':{x:0,y:0,name:'Taverna Maledetta',theme:'tavern',kind:'tavern',monster:null,loot:false}},count:1,gate:false,winner:null,event:'Tira il dado.',log:['La Taverna apre le porte.']};show('game');init3D();rebuild();ui()};
function ui(){if(!G)return;let a=A();$('turn').textContent=a.ai?'🤖 Turno IA — '+a.name:'🟡 Il tuo turno — '+a.name;$('event').textContent=G.event;$('sig').textContent=G.ps[0].sig;$('moves').textContent=G.moves;$('d1').textContent=['','⚀','⚁','⚂','⚃','⚄','⚅'][G.dice[0]];$('d2').textContent=['','⚀','⚁','⚂','⚃','⚄','⚅'][G.dice[1]];$('d2').classList.toggle('hidden',G.phase!=='combat');$('players').innerHTML=G.ps.map((p,i)=>`<div class="pr ${i===G.turn?'on':''}"><div class="pf">${HEROES[p.hi][2]}</div><div><b>${p.ai?'🤖 ':''}${p.name}</b><div class="small">🪙${p.coins} · 🔻${p.sig}/3 · 🍺${p.s}/10</div><div class="bar"><i style="width:${p.s*10}%"></i></div></div></div>`).join('');$('pad').classList.toggle('hidden',a.ai||G.phase!=='move'||G.moves<=0);$('rollBtn').disabled=a.ai||G.busy||G.phase!=='roll';$('abilityBtn').disabled=a.ai||G.busy;$('endBtn').disabled=a.ai||G.busy;$('log').innerHTML=G.log.slice().reverse().slice(0,18).map(x=>'<div>'+x+'</div>').join('')}
function modal(t,b,buttons){return new Promise(res=>{$('mt').textContent=t;$('mb').innerHTML='<p>'+b+'</p>';$('ma').innerHTML='';buttons.forEach(x=>{let z=document.createElement('button');z.className='btn '+(x[2]||'');z.textContent=x[0];z.onclick=()=>{$('overlay').classList.add('hidden');res(x[1])};$('ma').appendChild(z)});$('overlay').classList.remove('hidden')})}
function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.85})}function box(w,h,d,c){let m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.castShadow=m.receiveShadow=true;return m}function cyl(r,h,c){let m=new THREE.Mesh(new THREE.CylinderGeometry(r*.88,r,h,16),mat(c));m.castShadow=m.receiveShadow=true;return m}
