$('rollBtn').onclick=async()=>{if(G.busy||A().ai||G.phase!=='roll')return;G.busy=true;let [n]=await dice(1);G.moves=n;G.phase='move';G.event='Hai '+n+' passi.';G.log.push('🎲 '+A().name+' tira '+n);G.busy=false;ui()};
function newRoom(x,y){if(!G.gate&&G.count>=10&&Math.random()<.3){G.gate=true;return{x,y,name:'Porta della Sbornia Eterna',theme:'gate',kind:'gate',monster:null}}let z=THEMES[R(0,THEMES.length-1)],r={x,y,name:z[0],theme:z[1],kind:z[2],monster:null,loot:z[2]==='loot'};if(r.kind==='monster'||(r.kind==='mixed'&&Math.random()<.55)){let m=MON[R(0,MON.length-1)];r.monster={name:m[0],force:m[1],reward:m[2]}}return r}
$('pad').onclick=e=>{let b=e.target.closest('button[data-d]');if(b){let [x,y]=b.dataset.d.split(',').map(Number);move(x,y)}};
async function move(dx,dy){if(G.busy||A().ai||G.phase!=='move'||G.moves<=0)return;let p=A(),ox=p.x,oy=p.y,nx=ox+dx,ny=oy+dy;if(Math.abs(nx)>4||Math.abs(ny)>4)return toast('Muro');G.busy=true;let r=G.rooms[key(nx,ny)],fresh=!r;if(fresh){r=newRoom(nx,ny);G.rooms[key(nx,ny)]=r;G.count++;G.log.push('🚪 '+p.name+' scopre '+r.name);rebuild()}let m=pawns.get(p.id),w=wp(nx,ny);if(m)await tween(m,{x:w.x,y:0,z:w.z},550);p.x=nx;p.y=ny;G.moves--;cam();let out;if(fresh)out=await resolve(p,r,true);else if(r.monster)out=await fight(p,r,true);if(p.ko){G.moves=0;G.phase='end'}else if(G.moves>0)G.phase='move';else G.phase='end';G.busy=false;sync();ui()}
async function resolve(p,r,human){if(r.kind==='gate'){if(p.sig>=3)await boss(p,human);else G.event='Servono 3 Sigilli.';return}if(r.monster)return fight(p,r,human);if(r.kind==='curse'){if(p.hi===5&&!p.once&&human){let q=await modal('Maledizione','Morgana può annullarla.',[['ANNULLA','yes','purple'],['SUBISCI','no','red']]);if(q==='yes'){p.once=true;G.event='Maledizione annullata.';return}}p.s++;G.event='+1 Sbronza.'}else if(r.kind==='coin'){p.coins+=2;G.event='Trovi 2 monete.'}else if(r.kind==='heal'){p.s=Math.max(0,p.s-1);G.event='Recuperi: -1 Sbronza.'}else if(r.kind==='loot'){p.coins+=2;if(Math.random()<.45&&p.sig<3)p.sig++;G.event='Trovi un bottino.'}else G.event='Stanza tranquilla.';if(p.s>=10)KO(p)}
async function fight(p,r,human){let m=r.monster;if(human){let q=await modal('👹 '+m.name,'Forza '+m.force+'. Se perdi torni alla Taverna con i passi rimanenti.',[['ATTACCA','a',''],['FUGGI','f','alt']]);if(q==='f'){p.x=0;p.y=0;G.event='Fuggi alla Taverna.';sync();return{fled:true}}}let extra=0;if(human&&p.s<9){let q=await modal('Strategia','Tiro normale oppure +1 Sbronza per +2.',[['NORMALE','n',''],['CARICA +2','c','red']]);if(q==='c'){p.s++;extra=2}}let [a,b]=await dice(2);let total=a+b+drunk(p.s)+p.bonus+extra;p.bonus=0;if(p.s===9&&a===1&&b===1){KO(p);return}if(total>=m.force){p.coins+=m.reward;if(Math.random()<.33&&p.sig<3)p.sig++;r.monster=null;G.event='⚔️ '+p.name+' sconfigge '+m.name+' ('+total+'/'+m.force+').';G.log.push(G.event);sync();if(human)await modal('Vittoria',G.event,[['CONTINUA','ok','']])}else{p.s++;G.log.push('💥 '+p.name+' perde contro '+m.name);if(p.s>=10){KO(p);G.moves=0;if(human)await modal('KO','Sbronza 10: ritorni alla Taverna e il turno termina.',[['CONTINUA','ok','alt']])}else{p.x=0;p.y=0;sync();G.event='Sei stato battuto. Torni alla Taverna e conservi '+G.moves+' passi.';if(human)await modal('Sconfitta',G.event,[['CONTINUA IL TURNO','ok','alt']])}}G.phase=G.moves>0&&!p.ko?'move':'end';return{won:!r.monster}}
function KO(p){p.ko=true;p.s=5;p.coins=Math.floor(p.coins/2);p.x=0;p.y=0;G.event='💫 KO: ritorno alla Taverna, Sbronza 5.';G.log.push(G.event);sync()}
async function boss(p,h){let b=BOSSES[R(0,BOSSES.length-1)];if(h)await modal('👑 '+b[0],'Boss finale, Forza '+b[1]+'.',[['AFFRONTA','x','']]);let [a,c]=await dice(2),t=a+c+drunk(p.s);if(t>=b[1]){G.winner=p.name;G.event='🏆 '+p.name+' vince Taverna Maledetta!';if(h)await modal('VITTORIA!',G.event,[['CHIUDI','x','']])}else{p.s+=2;G.event='Il Boss ti respinge.';if(p.s>=10)KO(p)}}
$('abilityBtn').onclick=()=>{let p=A();if(p.hi===0){if(p.s>=9)return toast('Troppo sbronzo');p.s++;p.bonus+=2;G.event='Borik: +2 prossimo combattimento.'}else if(p.hi===1){if(p.used)return;p.used=true;p.bonus++;G.event='Merlò prepara +1.'}else if(p.hi===2){let ds=[[1,0],[-1,0],[0,1],[0,-1]].filter(d=>!G.rooms[key(p.x+d[0],p.y+d[1])]);if(ds.length){let d=ds[R(0,ds.length-1)],r=newRoom(p.x+d[0],p.y+d[1]);G.rooms[key(r.x,r.y)]=r;G.count++;rebuild();G.event='Elira rivela una stanza.'}}else if(p.hi===4){let v=G.ps.find(q=>q.id!==p.id&&q.x===p.x&&q.y===p.y&&q.coins>0);if(v&&R(1,6)>=4){v.coins--;p.coins++;G.event='Nix ruba 1 moneta.'}else G.event='Furto fallito.'}else G.event='L’abilità si attiva quando serve.';ui()};
$('endBtn').onclick=()=>{if(!A().ai&&!G.busy)next()};function next(){let p=A();p.ko=false;p.used=false;G.moves=0;G.phase='roll';G.dice=[1,1];G.turn=(G.turn+1)%G.ps.length;if(G.turn===0)G.round++;G.event=A().ai?'Turno IA: guarda il personaggio muoversi.':'Tocca a te. Tira il dado.';cam();ui();if(A().ai)setTimeout(ai,500)}
async function ai(){if(G.winner)return;G.busy=true;let p=A(),[n]=await dice(1);G.moves=n;G.phase='move';G.log.push('🤖 '+p.name+' tira '+n);for(let i=0;i<n;i++){if(p.ko||G.winner)break;let ds=[[1,0],[-1,0],[0,1],[0,-1]].filter(d=>Math.abs(p.x+d[0])<=4&&Math.abs(p.y+d[1])<=4),fresh=ds.filter(d=>!G.rooms[key(p.x+d[0],p.y+d[1])]),d=(fresh.length?fresh:ds)[R(0,(fresh.length?fresh:ds).length-1)],nx=p.x+d[0],ny=p.y+d[1],r=G.rooms[key(nx,ny)],nw=!r;if(nw){r=newRoom(nx,ny);G.rooms[key(nx,ny)]=r;G.count++;rebuild()}let pm=pawns.get(p.id),w=wp(nx,ny);if(pm)await tween(pm,{x:w.x,y:0,z:w.z},470);p.x=nx;p.y=ny;G.moves--;if(nw)await resolve(p,r,false);else if(r.monster)await fight(p,r,false);await sleep(180)}G.busy=false;G.phase='end';ui();setTimeout(next,380)}
document.addEventListener('keydown',e=>{if($('game').classList.contains('hidden'))return;if(e.key==='ArrowUp')move(0,-1);if(e.key==='ArrowDown')move(0,1);if(e.key==='ArrowLeft')move(-1,0);if(e.key==='ArrowRight')move(1,0)});
